filter:
    excluded_paths:
        - tests/*

checks:
    php:
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        return_doc_comments: true
        parameter_doc_comments: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        remove_extra_empty_lines: true
        phpunit_assertions: true
        optional_parameters_at_the_end: true
        newline_at_end_of_file: true
        function_in_camel_caps: true
        fix_line_ending: true
        encourage_single_quotes: true
        classes_in_camel_caps: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        return_doc_comment_if_not_inferrable: true
        param_doc_comment_if_not_inferrable: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
                size: 2
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
                else_on_new_line: true
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
                while_on_new_line: true
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

build:
    tests:
        override:
            -
                command: 'phpunit --configuration phpunit.xml --coverage-clover=some-file'
                idle_timeout: 600
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
