language: php
php:
    - 7.0
    - 7.1
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
  - composer self-update

install:
  - composer update --no-interaction --prefer-source --dev $COMPOSER_EXTRA_ARGS

script: phpunit --configuration phpunit.xml --coverage-text
